baseurl = "https://temocpalma.github.io/"
languageCode = "en-us"
title = "El Blog de Temoc"
theme = "retrofulhugo"
pygmentsUseClasses = true
googleAnalytics = "UA-105312001-1"
#disqusShortname = "XXX"

[Params]
  subtitle = "Beginner Programmer"
  logo = "img/ship.png"
  favicon = "img/icoprogramming.ico"
  commit = false

[Author]
	handle = "Temoc Palma"
  name = "Cuahthémoc Palma Gutiérrez"
  email = "temopalmag@gmail.com"
  github = "temocpalma"
  twitter = "cpalmag"
  facebook = "cuauh.palma"


#[[menu.main]]
#    name = "About"
#    url = "/page/about/"
#    weight = 2
