baseurl = "https://temocpalma.github.io/"
languageCode = "en-us"
title = "El Blog de Temoc"
theme = "docdock"
pygmentsUseClasses = true
googleAnalytics = "UA-105312001-1"
#disqusShortname = "XXX"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fa fa-user-circle'></i> Quién soy..."
url = "/about"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-address-book'></i> Sígueme"
url = "/socialnet"
weight = 20
